"""add_is_logged_in

Revision ID: 4ffd672a2105
Revises: 9cfec0852c7d
Create Date: 2026-06-11 07:03:56.440687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd672a2105'
down_revision: Union[str, None] = '9cfec0852c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_logged_in', sa.Boolean(), server_default=sa.text('true'), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_logged_in')
    # ### end Alembic commands ###
