"""add_required_channels_update_bot_settings

Revision ID: b6fa9999b75a
Revises: cbed1fefcbc3
Create Date: 2026-06-11 11:21:27.883029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fa9999b75a'
down_revision: Union[str, None] = 'cbed1fefcbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('required_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.drop_column('bot_settings', 'required_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_settings', sa.Column('required_channel', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_table('required_channels')
    # ### end Alembic commands ###
