"""add_bot_settings

Revision ID: cbed1fefcbc3
Revises: 4ffd672a2105
Create Date: 2026-06-11 11:01:15.449575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbed1fefcbc3'
down_revision: Union[str, None] = '4ffd672a2105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required_channel', sa.String(length=128), nullable=True),
    sa.Column('subscription_enabled', sa.Boolean(), nullable=False),
    sa.Column('webapp_url', sa.Text(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
