"""Bot-wide constants and FSM states."""

# ── Registration FSM ──
REG_WAITING_LOGIN = 0
REG_WAITING_PASSWORD = 1
REG_CHECK_SUBSCRIPTION = 2

# ── Admin FSM ──
ADM_MENU = 100
ADM_CHANNELS_LIST = 101
ADM_CHANNEL_ADD_ID = 102
ADM_CHANNEL_ADD_TITLE = 103
ADM_CHANNEL_ADD_LINK = 104
ADM_CHANNEL_DETAIL = 105
ADM_CHANNEL_EDIT = 106
ADM_CHANNEL_EDIT_INPUT = 107
ADM_USERS_MENU = 108
ADM_USERS_SEARCH = 109
ADM_USER_DETAIL = 110
ADM_USER_XP_INPUT = 111
ADM_USER_POINTS_INPUT = 112
ADM_BROADCAST_MENU = 113
ADM_BROADCAST_TEXT = 114
ADM_BROADCAST_PHOTO = 115
ADM_BROADCAST_BTN_TEXT = 116
ADM_BROADCAST_BTN_URL = 117
ADM_BROADCAST_TARGET = 118
ADM_BROADCAST_CONFIRM = 119
ADM_SETTINGS_WEBAPP = 120

# Test login lar (admin panelda ko'rinmasin)
TEST_LOGINS = frozenset({"api_admin", "api_teacher", "api_learner"})
